### ISSUE TITLE
Mac support, is there support or alternatives for Mac and Linux?

### ISSUE THREAD

**Issue by jjdd12** [SlimeVR/SlimeVR-OpenVR-Driver#42]

**Comment by ImUrX** [comment]
There is Monado, but it's a OpenXR Linux-only runtime, and we dont have a working driver for it yet.

Valve used to have OpenVR support for macOS but [it died](https://store.steampowered.com/news/app/250820/view/2216278054495230717). If you can run OpenVR games with no problem from Steam on Mac I will figure out how to build the SlimeVR driver for macOS, but it's not really a permanent solution.

**Comment by jjdd12** [comment]
I mostly need it for development as I do most of my development on Mac, but I can try to find a work around.
Thank you!
