### ISSUE TITLE
Driver crash with OVR space calibration and Natural Locomotion

### ISSUE THREAD

**Issue by Eirenliel** [SlimeVR/SlimeVR-OpenVR-Driver#9]
See here for info in NaLo: https://github.com/SlimeVR/SlimeVR-Server/issues/25

Affected user's discord: Tera#0564

**Comment by Quantum-Red** [comment]
Second for Natural Locomotion. Causes SteamVR to crash if both SlimeVR server and Natural Locomotion are running at the same time, regardless of launch order.

**Comment by TheButlah** [comment]
Seconded - coming from Vive trackers, this caused unexpected crashes. I figured it out on my own but this friction should ideally not exist. Also, would be cool to use both vive trackers and slimevr at the same time

**Comment by DrDillis** [comment]
Also as a third, same thine. Sorry if that's extremely redundant, in dire needs of this I am getting extra trackers from ALVR (using two quest 2's) it works amazingly well, but I cant use the slime vr diy kit I've built with it now since I cannot calibrate my space using this tool.

**Comment by Eirenliel** [comment]
Should be fixed in #14
